export interface RevenueCodeEntry {
  code: string;
  oldCode: string;
  title: string;
  titleNp: string;
  explanation: string;
}

export const REVENUE_CODES: RevenueCodeEntry[] = [
  { code: "11111", oldCode: "11111", title: "Tax on Sole Proprietorship and Individual Income", titleNp: "एकलौटी फर्म तथा व्यक्तिगत आयमा लाग्ने कर", explanation: "Includes tax on sole proprietorship firms and individual income." },
  { code: "11112", oldCode: "11112", title: "Remuneration Tax", titleNp: "पारिश्रमिक कर", explanation: "Includes tax levied on income of natural persons derived from employment, including salary, wages, remuneration, allowances and facilities, retirement payments, other employment-related payments, and lecturing/teaching." },
  { code: "11113", oldCode: "11113", title: "Capital Gains Tax (Individual)", titleNp: "पूँजीगत लाभ कर", explanation: "Includes capital gains tax levied on individuals and sole proprietorships from the disposal, sale, lease, or transfer of rights of assets such as houses, land, and shares." },
  { code: "11115", oldCode: "11135", title: "Windfall Gain Tax", titleNp: "आकस्मिक लाभ कर", explanation: "Includes tax on windfall gains received by individuals from gambling, lotteries, betting, gifts, donations, inheritances, rewards, and informant prizes." },
  { code: "11119", oldCode: "11120", title: "Other Tax on Income of Sole Proprietorship", titleNp: "एकलौटी व्यवशायको आयमा लाग्ने अन्य कर", explanation: "Includes other taxes falling under this category that are not specified in the above sub-heads." },
  { code: "11120", oldCode: "11121", title: "Tax on Income of Entities", titleNp: "निकायको आयमा लाग्ने कर", explanation: "Includes tax on income of business entities and institutions. (Note: Direct deposits cannot be made into this main head)." },
  { code: "11121", oldCode: "", title: "Tax on Profit of Entities - Government Corporations", titleNp: "निकायको मुनाफामा लाग्ने कर- सरकारी संस्थान", explanation: "Includes tax on the income of government entities or entities under government managerial control where the government holds full or majority (more than 50%) ownership." },
  { code: "11122", oldCode: "11122", title: "Tax on Profit of Entities (Public Limited Company)", titleNp: "निकायको मुनाफामा लाग्ने कर ( पब्लिक लिमिटेड कम्पनी )", explanation: "Includes tax on the income of Public Limited Companies registered under specific acts or the Company Act, and companies where government ownership is less than 50%." },
  { code: "11123", oldCode: "11123", title: "Tax on Profit of Entities (Private Limited Company)", titleNp: "निकायको मुनाफामा लाग्ने कर ( प्राइभेट लिमिटेड कम्पनी )", explanation: "Includes tax on the income of Private Limited Companies registered under the Company Act and other companies specified per the Income Tax Act." },
  { code: "11124", oldCode: "", title: "Tax on Profit of Entities (Other Institutions)", titleNp: "निकायको मुनाफामा लाग्ने कर ( अन्य संस्था )", explanation: "Includes tax on the income of entities other than those listed in codes 11121 to 11123, such as partnership firms, cooperatives, trusts, associations, foreign companies, and other bodies." },
  { code: "11125", oldCode: "11125", title: "Capital Gains Tax (Entities)", titleNp: "पूँजीगत लाभ कर निकाय", explanation: "Includes capital gains tax levied on entities from the disposal, sale, lease, or transfer of rights of assets such as houses, land, and shares." },
  { code: "11126", oldCode: "11135", title: "Windfall Gain Tax (Entities)", titleNp: "आकस्मिक लाभ कर", explanation: "Includes tax on windfall gains received by entities from lotteries, gifts, donations, inheritances, rewards, etc." },
  { code: "11129", oldCode: "", title: "Other Tax on Income of Entities", titleNp: "निकायको आयमा लाग्ने अन्य कर", explanation: "Includes other corporate income taxes not falling under any of the specifically mentioned heads." },
  { code: "11130", oldCode: "11130", title: "Tax on Investment Income and Other Income", titleNp: "लगानीको आय तथा अन्य आयमा लाग्ने कर", explanation: "Includes tax on other incomes not specified under heads 11111 to 11125. (Note: Direct deposits cannot be made into this head)." },
  { code: "11131", oldCode: "11131", title: "Tax on Income from Property Rent and Lease", titleNp: "सम्पत्ती, बहाल तथा पट्टा वापतको आयमा लाग्ने कर", explanation: "Includes tax on income received from renting or leasing house and land, as well as hiring out or leasing vehicles and other immovable properties under long-term contracts." },
  { code: "11132", oldCode: "11132", title: "Tax on Interest", titleNp: "व्याजमा लाग्ने कर", explanation: "Includes tax on interest paid or received from banks, finance companies, other entities, or individuals." },
  { code: "11133", oldCode: "11133", title: "Tax on Dividend", titleNp: "लाभांशमा लाग्ने कर", explanation: "Includes tax on dividends earned as a return on investment made in any company or entity." },
  { code: "11134", oldCode: "11134", title: "Other Tax on Investment Income", titleNp: "लगानी सम्बन्धी अन्य आयमा लाग्ने कर", explanation: "Includes other miscellaneous taxes on investment-related incomes." },
  { code: "11139", oldCode: "11139", title: "Tax on Other Income", titleNp: "अन्य आयमा लाग्ने कर", explanation: "Includes taxes on any other forms of income not listed in the specified code numbers above." },
  { code: "11200", oldCode: "11200", title: "Tax Based on Remuneration and Wages", titleNp: "पारिश्रमिक तथा ज्यालामा आधारित कर", explanation: "Includes taxes levied based on remuneration and wages. (Note: Direct deposits cannot be made into this main head)." },
  { code: "11210", oldCode: "", title: "Social Security Tax Based on Remuneration and Wages (Group Head)", titleNp: "पारिश्रमिक तथा ज्यालामा आधारित सामाजिक सुरक्षा कर", explanation: "Includes taxes levied based on remuneration and wages for social security. (Note: Direct deposits cannot be made into this head)." },
  { code: "11211", oldCode: "11211", title: "Social Security Tax Based on Remuneration and Wages", titleNp: "पारिश्रमिक तथा ज्यालामा आधारित सामाजिक सुरक्षा कर", explanation: "Includes the lump-sum social security tax collected as specified from the aggregate income of a natural person from employment (salary, wages, remuneration, allowances, facilities, retirement payments, etc.)." },
  { code: "11412", oldCode: "", title: "Luxury Fee", titleNp: "विलासिता शुल्क", explanation: "Includes fees levied on luxury goods and services such as services provided by 5-star or higher rated hotels and luxury resorts, imported liquor, and gold or precious jewelry studded with diamonds or pearls above a specified threshold value." },
  { code: "11442", oldCode: "11442", title: "Health Service Tax", titleNp: "स्वास्थ्य सेवा कर", explanation: "Includes tax on healthcare services provided by health institutions other than government and community hospitals." },
  { code: "11443", oldCode: "11443", title: "Education Service Tax (Educational Institutions)", titleNp: "शिक्षा सेवा कर (शैक्षिक संस्था )", explanation: "Includes the service fee levied on tuition fees for specified educational services provided by private educational institutions." },
  { code: "11444", oldCode: "11444", title: "Education Service Tax (Foreign Study)", titleNp: "शिक्षा सेवा कर (वैदेशिक अध्ययन)", explanation: "Includes the service fee levied on tuition/educational payments made by students going abroad for higher education." },
  { code: "11445", oldCode: "", title: "Digital Services Tax (DST)", titleNp: "विद्युतीय सेवा कर", explanation: "Includes tax levied on the transaction value of digital services provided by non-resident persons to consumers in Nepal, such as advertisement services, movies, data, downloads, cloud, gaming, mobile apps, internet and software updates, online education, and consulting services." },
  { code: "11454", oldCode: "", title: "Road Construction and Maintenance Tax", titleNp: "सडक निर्माण तथा संभार कर", explanation: "Includes taxes collected based on vehicle type at the Transport Management Office at the time of vehicle registration." },
  { code: "14193", oldCode: "", title: "Foreign Tourism Fee", titleNp: "वैदेशिक पर्यटन शुल्क", explanation: "Includes the fee levied on payments made by Nepali tourists traveling abroad for tourism. Such fee must be collected by foreign outbound tour operators at the time of package sale or by a firm/company during accounting of expenses for sending associated individuals abroad for business promotion." },
  { code: "14194", oldCode: "", title: "Foreign Employment Service Fee", titleNp: "बैदेशिक रोजगार सेवा शुल्क", explanation: "Includes the fee legally deducted from payments collected from individuals going for foreign employment by licensed foreign employment recruitment agencies." },
  { code: "14214", oldCode: "14214", title: "Telecommunication Service Fee", titleNp: "दूरसंचार सेवा शुल्क", explanation: "Includes the amount collected as telecommunication service charges." },
  { code: "14215", oldCode: "14215", title: "Telephone Ownership Fee", titleNp: "टेलिफोन स्वामित्वको शुल्क", explanation: "Includes the amount collected as telephone registration/ownership fee." },
  { code: "33311", oldCode: "33111", title: "Value Added Tax (VAT) - Production", titleNp: "मू. अ. कर (उत्पादन )", explanation: "Includes Value Added Tax (VAT) applicable when a manufacturer produces and sells goods." },
  { code: "33313", oldCode: "33113", title: "Value Added Tax (VAT) - Sales & Distribution", titleNp: "मू. अ. कर (वस्तु बिक्री र वितरण )", explanation: "Includes Value Added Tax (VAT) payable by wholesale and retail distributors." },
  { code: "33314", oldCode: "33114", title: "Value Added Tax (VAT) - Consultation & Contract", titleNp: "मू. अ. कर ( परामर्श तथा ठेक्का )", explanation: "Includes Value Added Tax (VAT) levied on all types of contract businesses and consulting services. (Note: Old contract taxes outstanding from before the implementation of VAT should also be deposited here if recovered)." },
  { code: "33315", oldCode: "33115", title: "Value Added Tax (VAT) - Tourism Service Collection", titleNp: "मू. अ. कर पर्यटन सेवा संकलन", explanation: "Includes Value Added Tax (VAT) on tourism-related businesses such as hotels, travel agencies, trekking, and rafting. (Note: Outstanding hotel taxes from before the VAT era should be deposited here upon recovery)." },
  { code: "33316", oldCode: "33116", title: "Value Added Tax (VAT) - Communication, Insurance, Flight & Other Services", titleNp: "मू. अ. कर (संचार सेवा, विमा, हवाई उडान र अन्य सेवा संकलन )", explanation: "Includes Value Added Tax (VAT) collected on the sale of all communication services (except government postal services), insurance, and other specified services, plus flight tax. (Note: Outstanding entertainment taxes collected from before the VAT implementation should also be deposited here)." },
  { code: "33317", oldCode: "33117", title: "Value Added Tax (VAT) - Collection from Unregistered Persons", titleNp: "मू. अ. कर बेदर्तावालाबाट गर्ने संकलन", explanation: "Includes VAT to be collected when acquiring services from an unregistered person outside Nepal, VAT on timber sales, and VAT collected/remitted by local levels, international organizations/missions in Nepal, government bodies, or public corporations dealing in VAT-exempt goods." },
  { code: "33331", oldCode: "33131", title: "Excise Duty - Tobacco Products", titleNp: "अन्तःशुल्क (सुर्तिजन्य पदार्थ )", explanation: "Includes excise duties levied on the production of all types of tobacco-related products." },
  { code: "33332", oldCode: "33132", title: "Excise Duty - Liquor", titleNp: "अन्तःशुल्क (मदिरा )", explanation: "Includes excise duties on the production of liquor (including wine and other light alcoholic beverages)." },
  { code: "33333", oldCode: "33133", title: "Excise Duty - Beer", titleNp: "अन्तःशुल्क ( बियर )", explanation: "Includes excise duty levied on the production of beer." },
  { code: "33334", oldCode: "33134", title: "Excise Duty - Other Industrial Production", titleNp: "अन्तःशुल्क (अन्य औद्योगिक उत्पादन )", explanation: "Includes excise duty on other industrial manufacturing/production not covered by sub-heads 33331, 33332, or 33333." },
];
